"""
Report Writer Agent
────────────────────
Applies the critic's feedback to produce the final polished report,
then saves it as a Markdown file.
"""
from __future__ import annotations

import os
from datetime import datetime
from pathlib import Path

from langchain_core.messages import HumanMessage, SystemMessage

from graph.state import ResearchState
from utils import get_llm, logger

SYSTEM = """You are a professional research editor. You receive a draft report and
a critique. Revise the report to address all the weaknesses and suggestions.
Keep all verified facts. Improve structure, clarity, and depth.
Return ONLY the final Markdown report — no preamble, no meta-commentary.
"""


def run(state: ResearchState) -> ResearchState:
    logger.section("Report Writer Agent", color="bright_green")

    draft = state.get("draft_report", "")
    critique = state.get("critique", "")
    needs_revision = state.get("needs_revision", False)
    query = state["query"]

    if needs_revision and critique:
        logger.agent_log("ReportWriter", "Revising based on critique…")
        llm = get_llm(temperature=0.2)
        resp = llm.invoke([
            SystemMessage(content=SYSTEM),
            HumanMessage(content=(
                f"Draft:\n{draft}\n\n"
                f"Critique:\n{critique}"
            )),
        ])
        final = resp.content.strip()
    else:
        logger.agent_log("ReportWriter", "Draft accepted — no major revision needed")
        final = draft

    # Append metadata footer
    cache_status = "Redis cache active" if _redis_ok() else "Redis unavailable (direct API)"
    footer = (
        f"\n\n---\n"
        f"*Generated by Multi-Agent Research System*  \n"
        f"*Query:* {query}  \n"
        f"*Date:* {datetime.now().strftime('%Y-%m-%d %H:%M')}  \n"
        f"*Infrastructure:* LangGraph · Groq LLM · Tavily Search · {cache_status}  \n"
    )
    final += footer

    # Save to disk
    out_dir = Path(os.getenv("REPORT_OUTPUT_DIR", "./reports"))
    out_dir.mkdir(parents=True, exist_ok=True)
    slug = query[:50].lower().replace(" ", "_").replace("/", "-")
    filename = f"report_{slug}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
    path = out_dir / filename
    path.write_text(final, encoding="utf-8")

    logger.success(f"Report saved → {path}")
    state["final_report"] = final
    state["report_path"] = str(path)
    return state


def _redis_ok() -> bool:
    from utils import cache
    return cache.is_available()
